### ISSUE TITLE
[Player] Player attack does not work when clicking on health UI of objects

### ISSUE THREAD

**Issue by tanwayne890** [CS3247-Game-Development-Team-6/Doodles#260]
sometimes when you try to attack but are clicking on something (not sure what tho maybe an enemy), Doodle doesn't attack

**Comment by trxe** [comment]
Enemy Health canvas

**Comment by Fenway17** [comment]
Requires text meshes and images to disable "raycast target" option
![image](https://user-images.githubusercontent.com/24566006/196040457-3f2746c3-259c-40de-ab59-f44e64809de2.png)
