### ISSUE TITLE
Water spider not immune to water effects & water + ice effects

### ISSUE THREAD

**Issue by tanwayne890** [CS3247-Game-Development-Team-6/Doodles#313]
https://user-images.githubusercontent.com/58804560/197233373-586192aa-f526-455d-8ed4-99d20b48b92a.mp4

**Comment by trxe** [comment]
Might not be just water spider, have to check on fire spider/ice spider also

**Comment by tanwayne890** [comment]
there is no elemental effects immune, only immune to the damage. [docs.](https://docs.google.com/document/d/1PoZOaz8e8pLPKZaSvB6jh-uGP1skEX3DWNRklMCS0o8/edit) so will close the issue @trxe
