### ISSUE TITLE
Victory screen and Loss screen text

### ISSUE THREAD

**Issue by trxe** [CS3247-Game-Development-Team-6/Doodles#375]
Replace the text for this
![image](https://user-images.githubusercontent.com/23572486/200147763-710db937-6b56-4f8b-8c44-865415ccc909.png)
 and this
![image](https://user-images.githubusercontent.com/23572486/200147803-c1176b40-35e8-4e6c-bdba-607aaf3329df.png)

**Comment by tanwayne890** [comment]
![image](https://user-images.githubusercontent.com/58804560/200150118-b93e6921-355a-4f8d-8a85-770f571f7bbe.png)

![image](https://user-images.githubusercontent.com/58804560/200150135-95f91227-147f-4e04-9443-843fefbebcde.png)
